name: Daily list sync

on:
  schedule:
    - cron: "30 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Generate new list
        run: go run tools/generate-list/main.go

      - name: Test
        run: go test ./...

      - name: Check for list changes
        continue-on-error: true
        id: changes
        run: git update-index --refresh && git diff-index HEAD

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
